name: ci

permissions:
  contents: read

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        api-level: [35]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Run Android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          emulator-options: -no-snapshot-save -no-window -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          arch: x86_64
          script: ./gradlew connectedAndroidTest --stacktrace

      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation-test-results ${{ matrix.api-level }}
          path: ./**/build/reports/androidTests/connected/**
